---
Name: wellknown-validation-middleware
After:
  - requestprocessors
---
SilverStripe\Core\Injector\Injector:
  WellKnownValidationGlobalMiddleware:
   class: 'LoveDuckie\SilverStripe\WellKnownValidation\Middleware\WellKnownValidationGlobalMiddleware'
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        WellKnownValidationGlobalMiddleware: '%$WellKnownValidationGlobalMiddleware'

---
Name: wellknown-validation-extensions
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - LoveDuckie\SilverStripe\WellKnownValidation\Extensions\WellKnownValidationConfigurationExtension